version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - lll
    - misspell
    - mnd
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    ginkgolinter:
      force-expect-to: true
      validate-async-intervals: true
    gosec:
      severity: medium
      confidence: medium
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 150
    mnd:
      ignored-numbers:
        - "0755"
      ignored-functions:
        - ^cobra\.RangeArgs$
        - ^cobra\.MaximumNArgs$
        - ^cobra\.MinimumNArgs$
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      ignore-names:
        - db
        - err
        - id
        - os
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
    wsl:
      strict-append: false
      force-case-trailing-whitespace: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: _snippet_test.go
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
